### ISSUE TITLE
CAM4Recorder.py fails to run due to indentation & syntax error.

### ISSUE THREAD

**Issue by artyom2035** [beaston02/CAM4Recorder#1]
Followed readme to install requirements & complete setup. When I run the script as a standard user or root both return the following indentation error.  

$ python3.5 CAM4Recorder.py
  File "CAM4Recorder.py", line 17
   while i <5:
   ^
IndentationError:  unexpected indent

I removed the indent and the that error went away.  Ran the script again and it returned a syntax error.  

$ python3.5 CAM4Recorder.py 
  File "CAM4Recorder.py", line 26
    return results
                     ^
SyntaxError: 'return' outside function

Any idea what is wrong?  Thanks in advance.

**Comment by alucard13s** [comment]
same shit for me. Something is wrong on the script.
I don't understant his other script are ok without problems.

**Comment by beaston02** [comment]
I completely forgot this issue was reported. I'll see if I can't get it fixed today.   

Sorry for the delay!

**Comment by beaston02** [comment]
Again, sorry for the slow fix. I just updated the code. I somehow removed the line defining the function to get the online models. I quickly tested it on my mac, and it is working well here. Im going to close the issue. Please let me know if you have any problems
